name: Contract Advisor Rag

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]


jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Use Python version 3.8
              uses: actions/setup-python@v3
              with:
                python-version: 3.8

            - name : Install dependencies
              run: pip install -r requirements.txt

            - name: Run linters
              run: |
                black .


    test:
      runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Use Python version 3.8
              uses: actions/setup-python@v3
              with:
                python-version: 3.8

            - name : Install dependencies
              run: pip install -r requirements.txt

            - name: Run Test
              run: pytest test/test_extract_text_from_pdf.py
